language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        packages:
          - g++
          - make
          - libfuse-dev
          - libboost-dev
          - libboost-system-dev
          - libboost-filesystem-dev
          - libboost-program-options-dev
          - libcrypto++-dev
  - os: linux
    dist: bionic
    sudo: required
    compiler: clang
    addons:
      apt:
        packages:
          - clang
          - make
          - libfuse-dev
          - libboost-dev
          - libboost-system-dev
          - libboost-filesystem-dev
          - libboost-program-options-dev
          - libcrypto++-dev
  - os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
          - boost
          - cryptopp
        casks:
          - osxfuse
        update: true

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      make CXX=${CXX};
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      perl -p -i -e 's/-lfuse /-lfuse_ino64 /g' wfs-fuse/Makefile;
      make;
    fi
