language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        packages:
          - g++
          - make
          - pkg-config
          - libfuse-dev
          - libboost-dev
          - libboost-system-dev
          - libboost-filesystem-dev
          - libboost-program-options-dev
          - libcrypto++-dev
  - os: linux
    dist: bionic
    sudo: required
    compiler: clang
    addons:
      apt:
        packages:
          - clang
          - make
          - pkg-config
          - libfuse-dev
          - libboost-dev
          - libboost-system-dev
          - libboost-filesystem-dev
          - libboost-program-options-dev
          - libcrypto++-dev
  - os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
          - pkg-config
          - boost
          - cryptopp
        casks:
          - osxfuse
        update: true

script:
  - make
